name: After Merge

on: workflow_dispatch

jobs:
  MergeAction:
    uses: dwanim/openmoonray/.github/workflows/SubmoduleUpdate.yml@main
    with:
      repo: "openmoonray"
      branch: "rwoods/CM-18876"
    secrets: inherit
